### PR TITLE
Wrapper

### PR DESCRIPTION
**Pull request by jomo**
EDIT by Dico:

This is what I believe to be all of the code we had for wrapper so far. I pretty much renamed 'wrapper' to 'api' here, and renamed the modules to make more sense. 

What I'd like to see is a system where we prefix all modules with api_ or with mod_, depending on the task they execute. The modules that contain a feature for other modules, such as all of these, are api_ modules, and modules that contain a feature for ingame, for the players of the server or the staff members, these are mod_ modules and are loaded by main.py.

Besides, I think we should group our imports into 4 kinds, this is all explained on the [wiki page](https://github.com/RedstonerServer/toolbox/wiki/6.-Creating-a-new-module)

### CODE REVIEW

**Comment by Dico200** [comment]
Yes, we could, I found those useful to distinguish what part of the code I'm working on and I thought it made it easier to tell.
I'm actually using 3 different types of comments,
This one to explain what a class or function does:
```
"""
  # Text here
  # More text here
"""
```

Furthermore, this one to clearly fence off parts of the code that work together to achieve something, such as the Arguments, and the Command registering:
```
"""################
# < TITLE HERE > #
################"""

And simply #'s to explain parts of the code which might seem complicated, so these are for when you're reading the code and trying to understand how it works/what it does.

If you dislike this style of commenting, which is new to me, please tell me what you'd change exactly :)
The main reason I'm using to many #'s in the second one, is because it's just hard to miss that way.

I'm indenting with #'s in the first one, because I like the way it's done in java and this is similar.

**Comment by Dico200** [comment]
Sorry for the undescriptive commit message with my api_command progress update, here's something that should explain in more detail:

I'm taking some of the lines of code out of Command's __init__ and making it something thats easier to use for... users of @Command, and making it easier to read and cleaner in general (imo), that is the part which registers the command I'm talking about now.
For the Argument part, I made an argument type named Argument.MESSAGE, which didn't make a lot of sense. I removed that. Then, I made a kinda clean way of adding new Argument types, where each argument type defines their own 'handler' for a passed argument somewhere in a line in the same place, not in the middle of other code in a completely different class. Those are the main changes I made.

If you want to know better what api_command offers, you should read the comments I added in the classes.

**Comment by jomo** [comment]
How about creating a commands *package* with multiple files separating the code where you're using fenced comments now?

Also, shouldn't the helpers file be named api_helpers?

**Comment by Dico200** [comment]
Regarding helpers, I think that's slightly outdated. Locally, I currently have a file called api_utils, in which I included pans new mysql_connect() class, and in which I plan to also add the @async and @sync decorations. Then, using the fenced off things, I thought adding some messaging functions, player related functions, etc, from helpers.py. But some functions in helpers such as toggle are actually not even working properly and not used at all. 
I like the idea of having a folder for it though, api/utils/messages, api/utils/mysql (or dbconnect, I like this one more), api/utils/player.... Such things could be cool and would make the files much cleaner. That way we also dont import litterally *everything* by importing helpers.

**Comment by Dico200** [comment]
I think this would be a good time to merge this branch with master. Anything against that?

**Comment by Dico200** [comment]
I would love to hear your opinions on a few things:
* main.py
* params.py
* subdirectories
* what should we do with the previous helper functions? Group them in a few different files and add them to api/utils is what I'm thinking, but tell me what you think.

**Comment by jomo** [comment]
Closing in favor of #2.

**Pull request closed without merging**
